# MPC5121 ADS Machine Support
obj-$(CONFIG_SND_SOC_MPC5121_ADS) += mpc5121_ads.o mpc5121_ac97.o

# Modified MPC5121 ADS I2S Machine Support
obj-$(CONFIG_SND_SOC_MPC5121_I2S) += mpc5121_i2s.o

# MPC5121 Platform Support
obj-$(CONFIG_SND_SOC_MPC5121) += mpc5121_psc.o mpc5121_pcm.o
